### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Oglopf** [OSC/bc_osc_codeserver#29]
## Context
Looking at the install instructions for this app one sees `scl` being used, but I'm not sure that is still the current way this app is being used.

## Questions
- Should this be updated to use `lmod` or `rpm` commands instead? 
- Do we use `scl` still or do other sites? 
- Should we just have different markdown headings to handle which method a sys-admin is deploying with?

**Comment by treydock** [comment]
SCL is used on the OnDemand host to load the environment on all RPM based systems.  It's not used on compute but very much used on the web node.  Lmod is only used on the compute environment.

**Comment by Oglopf** [comment]
Thanks for the clarity Trey. In that case those steps are fine since it is aimed at the admin and I'm going to close this out.
