### ISSUE TITLE
App opens incorrect URL

### ISSUE THREAD

**Issue by btsherid** [OSC/bc_osc_codeserver#34]
Hi,

When I click the blue Connect to VS Code button, the app tries to open /rnode/<%= host %>/<%= port %>/rnode/<%= host %>/<%= port %>.

If I rewrite the URL in the browser to /rnode/<%= host %>/<%= port %>?folder=/home/btsherid, then VS Code launches and seems to work fine.

I'm assuming the extra part of the URL is coming from the code of this app but I'm not sure where that is getting appended from. Any help figuring this out would be appreciated.

Thanks,
Brendan

**Comment by johrstrom** [comment]
What version of OnDemand are you running? I believe there's a patch in 2.0 for this issue. See this discourse topic for the same:

https://discourse.openondemand.org/t/vscode-4-60-and-getting-a-enter-password-prompt/2427/17

**Comment by btsherid** [comment]
We are running 1.8.20. I was able to update that regex on our dev server and verify that the issue is resolved. I'll push that out to production soon.

I'm also going to test updating to 3.0.

Thanks,
Brendan
