### ISSUE TITLE
Use linux host adapter instead of quick?

### ISSUE THREAD

**Issue by johrstrom** [OSC/bc_osc_codeserver#8]
I know there's been discussion around using quick or using the linux host adapter to connect to owns for this app. So, let's discuss that here.

**Comment by msquee** [comment]
I'm in favor of the host adapter, we can burn-in testing time on the adapter.

**Comment by johrstrom** [comment]
Fine by me, though I think we should use pitzer just because they're larger machines.

So this ticket isn't so much a question as it is a statement to get it done.

**Comment by treydock** [comment]
Use Pitzer.  They have more resources and 10GbE ethernet vs Owens which has 1GbE and frequently Owens login nodes are pegged with max bandwidth on their ethernet interfaces.

**Comment by msquee** [comment]
Closed by #9
